apiVersion: v1
kind: Service
metadata:
  name: test-master
  labels:
    release: "test"
    component: "test-spark-master"
spec:
  ports:
    - port: 7077
      targetPort: 7077
  selector:
    component: "test-spark-master"