kind: Service
apiVersion: v1
metadata:
  name:  {{STACK_NAME}}-jupyter
  namespace: {{NAMESPACE}}
  labels:
    app: {{STACK_NAME}}-jupyter
    stack: {{STACK_NAME}}
spec:
  selector:
    app:  {{STACK_NAME}}-jupyter
  type:  LoadBalancer
  ports:
  - port:  8888
    targetPort: 8888