apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{STACK_NAME}}-jupyter
  namespace: {{NAMESPACE}}
  labels:
    app: {{STACK_NAME}}-jupyter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{STACK_NAME}}-jupyter
    spec:
      containers:
      - name: jupyter
        image: markthebault/jupyter:0.1
        command: ["start-notebook.sh","--NotebookApp.password='{{JUPYTER_PASSWORD}}'"]
        ports:
        - name: jupyter-server
          containerPort: 8888