kind: Service
apiVersion: v1
metadata:
  name:  jupyter
  namespace: datascience-toot
  labels:
    app: jupyter
spec:
  selector:
    app:  jupyter
  type:  LoadBalancer
  ports:
  - port:  8888
    targetPort: jupyter-server