apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
      - name: jupyter
        image: jupyter/base-notebook
        command: ["start-notebook.sh","--NotebookApp.password='sha1:82444b712319:e18ea4690c88c2a5a257a87e759abb8f037f36e2'"]
        ports:
        - name: jupyter-server
          containerPort: 8888