kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{NAMESPACE}}
  name: allow-sparkui-ingress
spec:
  podSelector:
    matchLabels:
      component: {{STACK_NAME}}-spark-master
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 9090