apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{STACK_NAME}}-spark-worker
  namespace: {{NAMESPACE}}
  labels:
    release: "cluster"
    component: "{{STACK_NAME}}-spark-worker"
    stack: {{STACK_NAME}}
    app: {{STACK_NAME}}-spark-worker
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: "{{STACK_NAME}}-spark-worker"
  template:
    metadata:
      labels:
        release: "cluster"
        component: "{{STACK_NAME}}-spark-worker"
    spec:
      containers:
        - name: {{STACK_NAME}}-spark-worker
          image: markthebault/spark:spark-2.2.1-hadoop2.7.0
          command: ["/usr/local/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://{{STACK_NAME}}-spark-master:7077"]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
          env:
          - name: SPARK_DAEMON_MEMORY
            value: "1g"
          - name: SPARK_WORKER_MEMORY
            value: "1g"
          - name: SPARK_WORKER_WEBUI_PORT
            value: "8080"
