apiVersion: v1
kind: Service
metadata:
  name: cluster-master
  namespace: datascience-toot
  labels:
    release: "cluster"
    component: "cluster-spark-master"
spec:
  ports:
    - port: 7077
      targetPort: 7077
  selector:
    component: "cluster-spark-master"
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-livy
  namespace: datascience-toot
  labels:
    release: "cluster"
    component: "cluster-spark-master"
spec:
  ports:
    - port: 8998
      targetPort: 8998
  selector:
    component: "cluster-spark-master"
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-master-webui
  namespace: datascience-toot
  labels:
    release: cluster
    component: cluster-spark-master
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    component: "cluster-spark-master"
  type: LoadBalancer