apiVersion: v1
kind: Service
metadata:
  name: {{STACK_NAME}}-spark-master
  namespace: {{NAMESPACE}}
  labels:
    release: "cluster"
    component: "{{STACK_NAME}}-spark-master"
    stack: {{STACK_NAME}}
    app: {{STACK_NAME}}-spark-master

spec:
  ports:
    - port: 7077
      targetPort: 7077
  selector:
    component: "{{STACK_NAME}}-spark-master"
---
apiVersion: v1
kind: Service
metadata:
  name: {{STACK_NAME}}-livy
  namespace: {{NAMESPACE}}
  labels:
    release: "cluster"
    component: "{{STACK_NAME}}-spark-master"
    stack: {{STACK_NAME}}
    app: {{STACK_NAME}}-livy

spec:
  ports:
    - port: 8998
      targetPort: 8998
  selector:
    component: "{{STACK_NAME}}-spark-master"
---
apiVersion: v1
kind: Service
metadata:
  name: {{STACK_NAME}}-spark-master-webui
  namespace: {{NAMESPACE}}
  labels:
    release: cluster
    component: {{STACK_NAME}}-spark-master
    stack: {{STACK_NAME}}
    app: {{STACK_NAME}}-webui
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    component: "{{STACK_NAME}}-spark-master"
  type: LoadBalancer